CREATE TABLE Posts (
    _id INTEGER PRIMARY KEY AUTO_INCREMENT,
    title TEXT NOT NULL,
    body TEXT NOT NULL
)
CREATE TABLE Comments(
    _id INTEGER PRIMARY KEY AUTO_INCREMENT,
    content TEXT NOT NULL,
    PostId INTEGER NOT NULL,
    FOREIGN KEY(PostId) REFERENCES Posts(_id)
)